// src/app/components/pages/settings/settings.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-settings',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './settings.component.html',
  styleUrl: './settings.component.css'
})
export class SettingsComponent {

}

<div class="flex h-screen bg-black">
    <sidebar></sidebar>
    <div class="bg-gray-800 text-white">
          <div class="py-8 px-4 mx-auto text-center lg:py-16 lg:px-12 mr-0">
              <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-whte md:text-5xl lg:text-6xl dark:text-white">Settings</h1>
              <p class="mb-8 text-lg font-normal text-gray-300 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400">With the Saguenay social network, users can create groups based on their interests, whether sports, art or the environment. This makes it easy to bring together people who share the same passions and organize activities.</p>
          </div>
    </div>
  </div>

// src/components/pages/settings.tsx
export default function Settings() {
    return (
      <div>
        <h1>Settings</h1>
        <h3>
          With the Saguenay social network, users can create groups based on their
          interests, whether sports, art or the environment. This makes it easy to
          bring together people who share the same passions and organize
          activities.
        </h3>
      </div>
    );
  }
